### ISSUE TITLE
Failed to create GLFW window.

### ISSUE THREAD

**Issue by Cvar1984** [sparkecho/shooter#1]
Linux yourhead 4.9.0-8-686-pae #1 SMP Debian 4.9.130-2 (2018-10-27) i686 GNU/Linux
Package: libglfw3-dev
Version: 3.2.1-1
Package: libglm-dev
Version: 0.9.8.3-3

`
__libc_start_main(0x425e30, 1, 0xbf92b794, 0x441fc0 <unfinished ...>
_ZNSt8ios_base4InitC1Ev(0x44d570, 128, 4, 0x426f02)   = 0xb7475d2c
__cxa_atexit(0xb73805c0, 0x44d570, 0x44d164, 0x426f02) = 0
cos(0x51000000, 0xbff921fb, 0xb74721d0, 0x427626)     = 0x51000000
cos(0, 0, 0xb74721d0, 0x427626)                       = 0
sin(0, 0, 0xb74721d0, 0x427626)                       = 0
sin(0x51000000, 0xbff921fb, 0xb74721d0, 0x427626)     = 0
cos(0, 0, 0xb74721d0, 0x427626)                       = 0
sqrtf(0x3f800000, 0x252ab369, 0, 0x427013)            = 0x44d000
sqrtf(0x3f800000, 0x3f800000, 0, 0x427013)            = 0x44d000
sqrtf(0x3f800000, 0, 0x3f800000, 0x427013)            = 0x44d000
_ZNSt8ios_base4InitC1Ev(0x44d571, 0, 0, 0x428c9d)     = 2
__cxa_atexit(0xb73805c0, 0x44d571, 0x44d164, 0x428c9d) = 0
_ZNSt8ios_base4InitC1Ev(0x44d572, 0x44d571, 0x44d164, 0x428fcc) = 3
__cxa_atexit(0xb73805c0, 0x44d572, 0x44d164, 0x428fcc) = 0
_ZNSt8ios_base4InitC1Ev(0x44d5a4, 0x44d572, 0x44d164, 0x429af8) = 4
__cxa_atexit(0xb73805c0, 0x44d5a4, 0x44d164, 0x429af8) = 0
__cxa_atexit(0x42c824, 0x44d574, 0x44d164, 0x429af8)  = 0
__cxa_atexit(0x42c846, 0x44d58c, 0x44d164, 0x429af8)  = 0
glfwInit(0xb7740659, 0, 0xb775bad8, 0xbf92b448)       = 1
glfwWindowHint(0x22002, 3, 0xb7284000, 0x425e59)      = 0xb7716040
glfwWindowHint(0x22003, 3, 0xb7284000, 0x425e59)      = 0xb7716040
glfwWindowHint(0x22008, 0x32001, 0xb7284000, 0x425e59) = 0xb7716040
glfwCreateWindow(800, 600, 0x442084, 0)               = 0
_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(0xb74748c0, 0x442088, 0xb7284000, 0x425e59) = 0xb74748c0
_ZNSolsEPFRSoS_E(0xb74748c0, 0xb73f4da0, 0xb7284000, 0x425e59Failed to create GLFW window.
) = 0xb74748c0
glfwTerminate(0xb7740659, 0, 0xb775bad8, 0xbf92b448)  = 0
+++ exited (status 255) +++
`

**Comment by sparkecho** [comment]
Hi there, thanks for your feedback. But currently I don't have a Debian system. But I tried on 
Linux archlinux 4.19.1-arch1-1-ARCH #1 SMP  x86_64 GNU/Linux,
Package: glfw-x11 3.2.1-2
Package: glm 0.9.9.3-1
and the issue you described I can't reappear.
Could you please provide more informations? Such as the version of OpenGL you chose in GLAD, what you changed to make it run in your environment?

**Comment by Cvar1984** [comment]
its OpenGL 2.1 Mesa 13.0.6, GLSL 1.20
idk whut wrong, but on C everything is ok
![glfw](https://user-images.githubusercontent.com/32727560/49957515-acf93780-ff3a-11e8-945a-4fb570140168.png)

**Comment by sparkecho** [comment]
I do think that's the reason. Because of the use of OpenGL core profile, this program requires OpenGL version >= 3.3. 
BTW. In my system(arch Linux), Mesa 18.2.4, GLSL 7.9, you don't need to get the version that high, but you should get compatible versions.
And you can checkout the following link for more details.
https://learnopengl.com/Getting-started/OpenGL
Good luck!
